name:                tries
version:             0.0.5
github:              "athanclark/tries"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 Athan Clark"
category:            Data, Tree
synopsis:            Various trie implementations in Haskell

ghc-options: -Wall

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://git.localcooking.com/tooling/tries#readme>

dependencies:
  - base >= 4.8 && < 5.0
  - bytestring
  - bytestring-trie
  - composition
  - containers
  - deepseq
  - hashable
  - keys
  - rose-trees >= 0.0.2.1
  - semigroups
  - sets >= 0.0.5.2
  - unordered-containers
  - QuickCheck >= 2.9.2
  - quickcheck-instances

library:
  source-dirs: src

tests:
  tries-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - tries
    - containers
    - mtl
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - quickcheck-instances

benchmarks:
  tries-bench-lookup:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - tries
    - criterion
    - rose-trees
    - mtl
    - unordered-containers
    - containers

  tries-bench-lookup:
    main:                Main.hs
    source-dirs:         bench-lookup
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - tries
    - criterion
    - rose-trees
    - mtl
    - unordered-containers
    - containers
